In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [2]:
file_path = "loan_prediction.csv.csv"  # Path to uploaded file
df = pd.read_csv(file_path)

In [3]:
df

Loan_ID    Gender Married Dependents Education Self_Employed  \
0          0  LP001002    Male         No         0      Graduate   
1          1  LP001003    Male        Yes         1      Graduate   
2          2  LP001005    Male        Yes         0      Graduate   
3          3  LP001006    Male        Yes         0  Not Graduate   
4          4  LP001008    Male         No         0      Graduate   
..       ...       ...     ...        ...       ...           ...   
609      609  LP002978  Female         No         0      Graduate   
610      610  LP002979    Male        Yes        3+      Graduate   
611      611  LP002983    Male        Yes         1      Graduate   
612      612  LP002984    Male        Yes         2      Graduate   
613      613  LP002990  Female         No         0      Graduate   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0                No               5849         0.0               NaN   
1                No               4583      1508.0             128.0   
2               Yes               3000         0.0              66.0   
3                No               2583      2358.0             120.0   
4                No               6000         0.0             141.0   
..              ...                ...         ...               ...   
609              No               2900         0.0              71.0   
610              No               4106         0.0              40.0   
611              No               8072       240.0             253.0   
612              No               7583         0.0             187.0   
613             Yes               4583         0.0             133.0   

     Credit_History  Property_Area Loan_Status Unnamed: 13  
0             360.0            1.0       Urban           Y  
1             360.0            1.0       Rural           N  
2             360.0            1.0       Urban           Y  
3             360.0            1.0       Urban           Y  
4             360.0            1.0       Urban           Y  
..              ...            ...         ...         ...  
609           360.0            1.0       Rural           Y  
610           180.0            1.0       Rural           Y  
611           360.0            1.0       Urban           Y  
612           360.0            1.0       Urban           Y  
613           360.0            0.0   Semiurban           N  

[614 rows x 14 columns]

In [4]:
display(df.head())

Loan_ID    Gender Married Dependents Education Self_Employed  \
0        0  LP001002    Male         No         0      Graduate   
1        1  LP001003    Male        Yes         1      Graduate   
2        2  LP001005    Male        Yes         0      Graduate   
3        3  LP001006    Male        Yes         0  Not Graduate   
4        4  LP001008    Male         No         0      Graduate   

  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              No               5849         0.0               NaN   
1              No               4583      1508.0             128.0   
2             Yes               3000         0.0              66.0   
3              No               2583      2358.0             120.0   
4              No               6000         0.0             141.0   

   Credit_History  Property_Area Loan_Status Unnamed: 13  
0           360.0            1.0       Urban           Y  
1           360.0            1.0       Rural           N  
2           360.0            1.0       Urban           Y  
3           360.0            1.0       Urban           Y  
4           360.0            1.0       Urban           Y

In [5]:
df.fillna(df.median(numeric_only=True), inplace=True)  # Fill missing numerical values with median
df.fillna(df.mode().iloc[0], inplace=True)  # Fill categorical with mode

In [6]:
label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le  # Store label encoder for reverse mapping if needed

In [7]:
X = df.drop(columns=['Loan_Status'])  # Features
y = df['Loan_Status']  # Target

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [10]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [11]:
y_pred = rf.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)


In [15]:
precision = precision_score(y_test, y_pred, average='macro')  # or 'weighted'
recall = recall_score(y_test, y_pred, average='macro')  # Match the same for recall


In [17]:
recall = recall_score(y_test, y_pred, average='macro')

In [18]:
print("Model Performance:")
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model Performance:
Accuracy: 0.37
Precision: 0.38
Recall: 0.37
Confusion Matrix:
[[14 15  9]
 [ 6 21 15]
 [10 22 11]]
